version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: on-failure

  backend:
    image: limic/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/media
    depends_on:
      - db
    restart: on-failure

  frontend:
    env_file: .env
    image: limic/foodgram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
    restart: on-failure

  gateway:
    image: limic/foodgram_gateway
    env_file: .env
    ports:
      - ${FOODGRAM_PORT}:80
    volumes:
      - static:/static
      - media:/media
    restart: on-failure